export const woInfo = [
    {
        "DeviceID": 1,
        "IP_Address": "192.168.1.100",
        "Platform": "HP",
        "CAS IP": "192.168.1.211",
        "Switch IP": "192.168.1.1",
        "DeviceType": "PSX",
        "Hardware (other name)": "Appliance",
        "ASI Cards": 4,
        "Rack": 36,
        "Location": "Keshet lab",
        "Description": "Main server",
        "Owner": "John Doe",
        "UsedBy": "John Doe",
        "LastUsed": "2023-09-04",
        "Loanable": "No"
    },
    {
        "DeviceID": 1,
        "IP_Address": "192.168.1.100",
        "Platform": "HP",
        "CAS IP": null,
        "Switch IP": "192.168.1.2",
        "DeviceType": "PSX",
        "Hardware (other name)": "Docker",
        "ASI Cards": 4,
        "Rack": 37,
        "Location": "Keshet lab",
        "Description": "Main server",
        "Owner": "John Doe",
        "UsedBy": "John Doe",
        "LastUsed": "2023-09-04",
        "Loanable": "No"
    },
    {
        "DeviceID": 1,
        "IP_Address": "192.168.1.100",
        "Platform": "HP",
        "CAS IP": null,
        "Switch IP": "192.168.1.3",
        "DeviceType": "PSX",
        "Hardware (other name)": "VM",
        "ASI Cards": 4,
        "Rack": 38,
        "Location": "Keshet lab",
        "Description": "Main server",
        "Owner": "John Doe",
        "UsedBy": "John Doe",
        "LastUsed": "2023-09-04",
        "Loanable": "No"
    },
    {
        "DeviceID": 2,
        "IP_Address": "192.168.1.1",
        "Platform": "Intel",
        "CAS IP": null,
        "Switch IP": "192.168.1.4",
        "DeviceType": "Router",
        "Hardware (other name)": null,
        "ASI Cards": null,
        "Rack": 39,
        "Location": "Cable OS",
        "Description": "Lab network gateway",
        "Owner": "IT Department",
        "UsedBy": "John Doe",
        "LastUsed": "2023-08-30",
        "Loanable": "Yes"
    },
    {
        "DeviceID": 3,
        "IP_Address": "192.168.1.2",
        "Platform": "Intel",
        "CAS IP": "192.168.1.212",
        "Switch IP": "192.168.1.5",
        "DeviceType": "Switch",
        "Hardware (other name)": null,
        "ASI Cards": null,
        "Rack": 40,
        "Location": "CS LAB",
        "Description": "Lab network switch",
        "Owner": "Mary Smith",
        "UsedBy": "Mary Smith",
        "LastUsed": "2023-09-01",
        "Loanable": "Yes"
    },
    {
        "DeviceID": 4,
        "IP_Address": "192.168.1.3",
        "Platform": "Intel",
        "CAS IP": "192.168.1.213",
        "Switch IP": "192.168.1.6",
        "DeviceType": "NMX",
        "Hardware (other name)": null,
        "ASI Cards": null,
        "Rack": 41,
        "Location": "CS LAB",
        "Description": "Lab network switch",
        "Owner": "Mary Smith",
        "UsedBy": "Mary Smith",
        "LastUsed": "2023-09-02",
        "Loanable": "Yes"
    },
    {
        "DeviceID": 5,
        "IP_Address": "192.168.1.4",
        "Platform": "Intel",
        "CAS IP": "192.168.1.214",
        "Switch IP": "192.168.1.7",
        "DeviceType": "ProView",
        "Hardware (other name)": null,
        "ASI Cards": null,
        "Rack": 42,
        "Location": "CS LAB",
        "Description": "Lab network switch",
        "Owner": "Mary Smith",
        "UsedBy": "Mary Smith",
        "LastUsed": "2023-09-03",
        "Loanable": "Yes"
    },
    {
        "DeviceID": 6,
        "IP_Address": "192.168.1.5",
        "Platform": "Intel",
        "CAS IP": "192.168.1.215",
        "Switch IP": "192.168.1.8",
        "DeviceType": "XOS",
        "Hardware (other name)": null,
        "ASI Cards": null,
        "Rack": 43,
        "Location": "CS LAB",
        "Description": "Lab network switch",
        "Owner": "Mary Smith",
        "UsedBy": "Mary Smith",
        "LastUsed": "2023-09-04",
        "Loanable": "Yes"
    }
];